<script>
import { Line } from "vue-chartjs";
import {  mapGetters } from 'vuex';

export default {
    extends: Line,
   
    data() {
        return {
        gradient: null,
        gradient2: null,
        
        estados: {
            aguascalientes: [],
            bajaCalifornia: [],
            bajaCaliforniaSur: [],
            campeche: [],
            chiapas: [],
            chihuahua: [],
            cdmx: [],
            coahuila: [],
            colima: [],
            durango: [],
            guanajuato: [],
            guerrero: [],
            hidalgo: [],
            jalisco: [],
            michoacan: [],
            morelos: [],
            mexico: [],
            nayarit: [],
            nuevoLeon: [],
            oaxaca: [],
            puebla: [],
            queretaro: [],
            quintanaroo: [],
            sanLuis: [],
            sinaloa: [],
            sonora: [],
            tabasco: [],
            tamaulipas: [],
            tlaxcala: [],
            veracruz: [],
            yucatan: [],
            zacatecas: []
        },
        

        fechas: [],
    };
  },
  computed:{
    ...mapGetters(['getEstados','getFechas'])
  },
  mounted() {
    
    
    this.estados = this.getEstados
    this.fechas = this.getFechas
    
    
    //await this.getListData();
    
    this.renderChart(
      {
        labels: this.fechas,
        datasets: [
            {
            label: "Aguascalientes",
            borderColor: "#18F610",
            pointBackgroundColor: "#18F610",
            borderWidth: 1,
            pointBorderColor: "#18F610",
            backgroundColor: this.gradient,
            data: this.estados.aguascalientes,
            hidden: true,
            fill: false,
          },
          {
            label: "Baja California",
            borderColor: "#10B6F6",
            pointBackgroundColor: "#10B6F6",
            borderWidth: 1,
            pointBorderColor: "#10B6F6",
            backgroundColor: this.gradient,
            data: this.estados.bajaCalifornia,
            hidden: true,
            fill: false,
          },
          {
            label: "Baja California Sur",
            borderColor: "#F61010",
            pointBackgroundColor: "#F61010",
            borderWidth: 1,
            pointBorderColor: "#F61010",
            backgroundColor: this.gradient,
            data: this.estados.bajaCaliforniaSur,
            hidden: true,
            fill: false,
          },
          {
            label: "Campeche",
            borderColor: "#DDF610",
            pointBackgroundColor: "#DDF610",
            borderWidth: 1,
            pointBorderColor: "#DDF610",
            backgroundColor: this.gradient,
            data: this.estados.campeche,
            hidden: true,
            fill: false,
          },
          {
            label: "Chiapas",
            borderColor: "#764F4F",
            pointBackgroundColor: "#764F4F",
            borderWidth: 1,
            pointBorderColor: "#764F4F",
            backgroundColor: this.gradient,
            data: this.estados.chiapas,
            hidden: true,
            fill: false,
          },
          {
            label: "Chihuahua",
            borderColor: "#F4C5DB",
            pointBackgroundColor: "#F4C5DB",
            pointBorderColor: "#F4C5DB",
            borderWidth: 1,
            backgroundColor: this.gradient,
            data: this.estados.chihuahua,
            hidden: true,
            fill: false,
          },
           {
            label: "CDMX",
            borderColor: "#CF3FD8",
            pointBackgroundColor: "#CF3FD8",
            pointBorderColor: "#CF3FD8",
            borderWidth: 1,
            backgroundColor: this.gradient2,
            data: this.estados.cdmx,
            hidden: true,
            fill: false,
          },
          {
            label: "Coahuila",
            borderColor: "#FB7404",
            pointBackgroundColor: "#FB7404",
            borderWidth: 1,
            pointBorderColor: "#FB7404",
            backgroundColor: this.gradient,
            data: this.estados.coahuila,
            hidden: true,
            fill: false,
          },
          {
            label: "Colima",
            borderColor: "#A71201",
            pointBackgroundColor: "#A71201",
            borderWidth: 1,
            pointBorderColor: "#A71201",
            backgroundColor: this.gradient,
            data: this.estados.colima,
            hidden: true,
            fill: false,
          },
          {
            label: "Durango",
            borderColor: "#A701A0",
            pointBackgroundColor: "#A701A0",
            borderWidth: 1,
            pointBorderColor: "#A701A0",
            backgroundColor: this.gradient,
            data: this.estados.durango,
            hidden: true,
            fill: false,
          },
          {
            label: "Guanajuato",
            borderColor: "#010CA7",
            pointBackgroundColor: "#010CA7",
            borderWidth: 1,
            pointBorderColor: "#010CA7",
            backgroundColor: this.gradient,
            data: this.estados.guanajuato,
            hidden: true,
            fill: false,
          },
          {
            label: "Guerrero",
            borderColor: "#0A6932",
            pointBackgroundColor: "#0A6932",
            borderWidth: 1,
            pointBorderColor: "#0A6932",
            backgroundColor: this.gradient,
            data: this.estados.guerrero,
            hidden: true,
            fill: false,
          },
          {
            label: "Hidalgo",
            borderColor: "#F65FE9",
            pointBackgroundColor: "#F65FE9",
            borderWidth: 1,
            pointBorderColor: "#F65FE9",
            backgroundColor: this.gradient,
            data: this.estados.hidalgo,
            hidden: true,
            fill: false,
          },         
          {
            label: "Jalisco",
            borderColor: "#CF5FF6",
            pointBackgroundColor: "#CF5FF6",
            borderWidth: 1,
            pointBorderColor: "#CF5FF6",
            backgroundColor: this.gradient,
            data: this.estados.jalisco,
            hidden: true,
            fill: false,
          },
           {
            label: "Michoacan",
            borderColor: "#EEC20A",
            pointBackgroundColor: "#EEC20A",
            borderWidth: 1,
            pointBorderColor: "#EEC20A",
            backgroundColor: this.gradient,
            data: this.estados.michoacan,
            hidden: true,
            fill: false,
          },
           {
            label: "Morelos",
            borderColor: "#396D08",
            pointBackgroundColor: "#396D08",
            borderWidth: 1,
            pointBorderColor: "#396D08",
            backgroundColor: this.gradient,
            data: this.estados.morelos,
            hidden: true,
            fill: false,
          },
           {
            label: "Mexico",
            borderColor: "#B1DB8A",
            pointBackgroundColor: "#B1DB8A",
            borderWidth: 1,
            pointBorderColor: "#B1DB8A",
            backgroundColor: this.gradient,
            data: this.estados.mexico,
            hidden: true,
            fill: false,
          },
           {
            label: "Nayarit",
            borderColor: "#00FBF4",
            pointBackgroundColor: "#00FBF4",
            borderWidth: 1,
            pointBorderColor: "#00FBF4",
            backgroundColor: this.gradient,
            data: this.estados.nayarit,
            hidden: true,
            fill: false,
          },
          {
            label: "Nuevo Leon",
            borderColor: "#177673",
            pointBackgroundColor: "#177673",
            pointBorderColor: "#177673",
            borderWidth: 1,
            backgroundColor: this.gradient2,
            data: this.estados.nuevoLeon,
            hidden: true,
            fill: false,
          },
           {
            label: "Oaxaca",
            borderColor: "#1081EA",
            pointBackgroundColor: "#1081EA",
            borderWidth: 1,
            pointBorderColor: "#1081EA",
            backgroundColor: this.gradient,
            data: this.estados.oaxaca,
            hidden: true,
            fill: false,
          },
            {
            label: "Puebla",
            borderColor: "#485594",
            pointBackgroundColor: "#485594",
            borderWidth: 1,
            pointBorderColor: "#485594",
            backgroundColor: this.gradient,
            data: this.estados.puebla,
            hidden: true,
            fill: false,
          },
           {
            label: "Queretaro",
            borderColor: "#0721A3",
            pointBackgroundColor: "#0721A3",
            borderWidth: 1,
            pointBorderColor: "#0721A3",
            backgroundColor: this.gradient,
            data: this.estados.queretaro,
            hidden: true,
            fill: false,
          },
           {
            label: "Quintana Roo",
            borderColor: "#5328E1",
            pointBackgroundColor: "#5328E1",
            borderWidth: 1,
            pointBorderColor: "#5328E1",
            backgroundColor: this.gradient,
            data: this.estados.quintanaroo,
            hidden: true,
            fill: false,
          },
           {
            label: "San Luis Potosi",
            borderColor: "#2F1978",
            pointBackgroundColor: "#2F1978",
            borderWidth: 1,
            pointBorderColor: "#2F1978",
            backgroundColor: this.gradient,
            data: this.estados.sanLuis,
            hidden: true,
            fill: false,
          },
           {
            label: "Sinaloa",
            borderColor: "#8054A5",
            pointBackgroundColor: "#8054A5",
            borderWidth: 1,
            pointBorderColor: "#8054A5",
            backgroundColor: this.gradient,
            data: this.estados.sinaloa,
            hidden: true,
            fill: false,
          },
           {
            label: "Sonora",
            borderColor: "#F000F2",
            pointBackgroundColor: "#F000F2",
            borderWidth: 1,
            pointBorderColor: "#F000F2",
            backgroundColor: this.gradient,
            data: this.estados.sonora,
            hidden: true,
            fill: false,
          },
           {
            label: "Tabasco",
            borderColor: "#931994",
            pointBackgroundColor: "#931994",
            borderWidth: 1,
            pointBorderColor: "#931994",
            backgroundColor: this.gradient,
            data: this.estados.tabasco,
            hidden: true,
            fill: false,
          },
           {
            label: "Tamaulipas",
            borderColor: "#941963",
            pointBackgroundColor: "#941963",
            borderWidth: 1,
            pointBorderColor: "#941963",
            backgroundColor: this.gradient,
            data: this.estados.tamaulipas,
            hidden: true,
            fill: false,
          },
           {
            label: "Tlaxcala",
            borderColor: "#9C4C7C",
            pointBackgroundColor: "#9C4C7C",
            borderWidth: 1,
            pointBorderColor: "#9C4C7C",
            backgroundColor: this.gradient,
            data: this.estados.tlaxcala,
            hidden: true,
            fill: false,
          },
           {
            label: "Veracruz",
            borderColor: "#E7135E",
            pointBackgroundColor: "#E7135E",
            borderWidth: 1,
            pointBorderColor: "#E7135E",
            backgroundColor: this.gradient,
            data: this.estados.veracruz,
            hidden: true,
            fill: false,
          },
           {
            label: "Yucatan",
            borderColor: "#CC557F",
            pointBackgroundColor: "#CC557F",
            borderWidth: 1,
            pointBorderColor: "#CC557F",
            backgroundColor: this.gradient,
            data: this.estados.yucatan,
            hidden: true,
            fill: false,
          },
           {
            label: "Zacatecas",
            borderColor: "#CC555B",
            pointBackgroundColor: "#CC555B",
            borderWidth: 1,
            pointBorderColor: "#CC555B",
            backgroundColor: this.gradient,
            data: this.estados.zacatecas,
            hidden: true,
            fill: false,
          },
        ]
      },
      { responsive: true, maintainAspectRatio: false }
    );
  },  
}
</script>

<style>

</style>